name: Bump Dolt on Winget

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'SemVer format release tag, i.e. 0.24.5'
        required: true
  repository_dispatch:
    types: [ bump-winget ]

jobs:
  winget-bump:
    name: Bump Dolt Winget
    runs-on: windows-2019
    defaults:
      run:
        shell: powershell
    steps:
      - name: Create Winget PR
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate.exe update DoltHub.Dolt -u $Env:URL -v $Env:VERSION -t $Env:TOKEN --submit
        env:
          TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
          URL: ${{ format('https://github.com/dolthub/dolt/releases/download/v{0}/dolt-windows-amd64.msi', github.event.inputs.version) }}
      - name: Create Winget PR
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate.exe update DoltHub.Dolt -u $Env:URL -v $Env:VERSION -t $Env:TOKEN --submit
        env:
          TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          VERSION: ${{ github.event.client_payload.version }}
          URL: ${{ format('https://github.com/dolthub/dolt/releases/download/{0}/dolt-windows-amd64.msi', github.event.client_payload.version) }}
